version: '3'
services:
  nginx:
    image: nginx:mainline
    volumes:
      - roothtml:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php:ro
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
      - ./nginx/nginx.template:/etc/nginx/conf.d/wordpress.template:ro
    ports:
      - 8080:80
    command: /bin/bash -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      NGINX_PORT: 80
    restart: always
    networks:
      nbc-wordpress-network:
          aliases:
            - nbc-wp-nginx

  wordpress-php:
    image: nbc-wordpress
    environment:
        - DB_NAME=wordpress_default
        - DB_USER=root
        - DB_PASS=toor
        - DB_HOST=nbc-wp-db
    build:
      context: ./wordpress
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
      - roothtml:/var/www/html
    networks:
      nbc-wordpress-network:
        aliases:
          - nbc-wp-php

  db:
    ports:
      - 33306:3306
    restart: always
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=wordpress_default
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      nbc-wordpress-network:
        aliases:
          - nbc-wp-db

networks:
  nbc-wordpress-network:

volumes:
  roothtml: