version: '3'
services:
  wordpress:
    ports:
      - 8080:80
    image: nbc-wordpress
    environment:
        - DB_NAME=wordpress_default
        - DB_USER=root
        - DB_PASS=toor
        - DB_HOST=nbc-wp-db
    build:
      context: ./wordpress
    volumes:
      - ./wordpress/nbc-wp-content:/var/www/html/wp-content
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    networks:
      nbc-wordpress-network:
        aliases:
          - nbc-wp-web

  db:
    restart: always
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=wordpress_default
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      nbc-wordpress-network:
        aliases:
          - nbc-wp-db

networks:
  nbc-wordpress-network: